# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MSjYibUwS29zwYib-IThZReUgH5WntUa
"""

# -*- coding: utf-8 -*-
import socket
from simplecrypt import encrypt, decrypt

HOST = '127.0.0.1'
PORT = 8000

passkey = 'ntu'

# TODO: write your codes here

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.bind((HOST, PORT))
server.listen(10)
while True:
    conn, addr = server.accept()
    clientMessage = conn.recv(1024)

    print('Client message is:', clientMessage.decode("utf-8"))

    passkey = 'ntu'
    cipher = encrypt(passkey, clientMessage) 
    conn.sendall(cipher)
    conn.close()
